package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CmpType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CmpType() {
    super(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x62cf56e9000aa904L, "CmpType", "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/7120005094624110852");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_LESS_0 = new EnumerationDescriptor.MemberDescriptor("LESS", "<", 0x62cf56e9000aa906L, "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/7120005094624110854");
  private final EnumerationDescriptor.MemberDescriptor myMember_LESS_OR_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("LESS_OR_EQUAL", "<=", 0x62cf56e9000aa909L, "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/7120005094624110857");
  private final EnumerationDescriptor.MemberDescriptor myMember_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("EQUAL", "==", 0x62cf56e9000aa90dL, "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/7120005094624110861");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_0 = new EnumerationDescriptor.MemberDescriptor("GREATER", ">", 0x62cf56e9000aa912L, "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/7120005094624110866");
  private final EnumerationDescriptor.MemberDescriptor myMember_GREATER_OR_EQUAL_0 = new EnumerationDescriptor.MemberDescriptor("GREATER_OR_EQUAL", ">=", 0x62cf56e9000aa918L, "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/7120005094624110872");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x62cf56e9000aa904L, 0x62cf56e9000aa906L, 0x62cf56e9000aa909L, 0x62cf56e9000aa90dL, 0x62cf56e9000aa912L, 0x62cf56e9000aa918L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_LESS_0, myMember_LESS_OR_EQUAL_0, myMember_EQUAL_0, myMember_GREATER_0, myMember_GREATER_OR_EQUAL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "LESS":
        return myMember_LESS_0;
      case "LESS_OR_EQUAL":
        return myMember_LESS_OR_EQUAL_0;
      case "EQUAL":
        return myMember_EQUAL_0;
      case "GREATER":
        return myMember_GREATER_0;
      case "GREATER_OR_EQUAL":
        return myMember_GREATER_OR_EQUAL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
