package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_LEDValue extends EnumerationDescriptorBase {

  public EnumerationDescriptor_LEDValue() {
    super(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0xa409fb9ce2a54d3L, "LEDValue", "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/738765959265408211");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "HIGH", 0xa409fb9ce2a54d4L, "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/738765959265408212");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOW_0 = new EnumerationDescriptor.MemberDescriptor("LOW", "LOW", 0xa409fb9ce2a5671L, "r:905d0be1-fff1-42bb-bb18-49da0f1243fb(NewLanguage.structure)/738765959265408625");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0xa409fb9ce2a54d3L, 0xa409fb9ce2a54d4L, 0xa409fb9ce2a5671L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_HIGH_0, myMember_LOW_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "HIGH":
        return myMember_HIGH_0;
      case "LOW":
        return myMember_LOW_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
