package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class PitchActuator_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.pitch$FosQ) == 0) {
      tgs.append("tone(");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.actuator$wrgP), PROPS.name$qsqd));
      tgs.append(", ");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.currentState$XGh0));
      tgs.append("};\n");
    } else {
      tgs.append("noTone(");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.actuator$wrgP), PROPS.name$qsqd));
      tgs.append(");\n");
    }
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink actuator$wrgP = MetaAdapterFactory.getReferenceLink(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x6be0c4403d48a0e3L, 0x6be0c4403d48a48eL, "actuator");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$qsqd = MetaAdapterFactory.getProperty(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x62cf56e9000abf07L, 0x62cf56e9000abfbeL, "name");
    /*package*/ static final SProperty currentState$XGh0 = MetaAdapterFactory.getProperty(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x6be0c4403d48a0e3L, 0x6be0c4403d48a1ceL, "currentState");
    /*package*/ static final SProperty pitch$FosQ = MetaAdapterFactory.getProperty(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x6be0c4403d4cfdaeL, 0x6be0c4403d4d274bL, "pitch");
  }
}
