package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class State_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("void ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$JdHN));
    tgs.append("() {\n");
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("while(1) {\n");
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.actuatorState$R3Zy)) {
      tgs.appendNode(item);
    }
    tgs.indent();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.transaction$oo3E));
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("}\n");
    ctx.getBuffer().area().decreaseIndent();
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.nextState$SrYF), PROPS.name$JdHN));
    tgs.append("();\n");
    tgs.append("};\n");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$JdHN = MetaAdapterFactory.getProperty(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x62cf56e9000a589aL, 0x62cf56e9000a58e9L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink actuatorState$R3Zy = MetaAdapterFactory.getContainmentLink(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x62cf56e9000a589aL, 0x6be0c4403d489353L, "actuatorState");
    /*package*/ static final SContainmentLink transaction$oo3E = MetaAdapterFactory.getContainmentLink(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x62cf56e9000a589aL, 0x70fdfc205b84e540L, "transaction");
    /*package*/ static final SReferenceLink nextState$SrYF = MetaAdapterFactory.getReferenceLink(0x3129c9e0bc3c4036L, 0x815e27f12b196e5eL, 0x62cf56e9000a589aL, 0x75183f7f14ddefe3L, "nextState");
  }
}
